version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      target: dev  # dev ou prod
    container_name: taskforge_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    networks:
      - taskforge_network

networks:
  taskforge_network: